# Generated by Django 6.0 on 2026-01-12 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIBehaviorConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tone', models.CharField(choices=[('friendly', 'Friendly & Warm'), ('professional', 'Professional'), ('sales', 'Sales-Oriented')], default='friendly', max_length=30)),
                ('retry_attempts_before_transfer', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3)),
                ('fallback_response', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_behavior_config', to='store.store')),
            ],
        ),
        migrations.CreateModel(
            name='GreetingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_hours_greeting', models.TextField()),
                ('closed_hours_message', models.TextField()),
                ('ai_behavior_config', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='greetings', to='ai_behavior.aibehaviorconfig')),
            ],
        ),
        migrations.CreateModel(
            name='AutoTransferKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=150)),
                ('ai_behavior_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_transfer_keywords', to='ai_behavior.aibehaviorconfig')),
            ],
            options={
                'unique_together': {('ai_behavior_config', 'keyword')},
            },
        ),
        migrations.CreateModel(
            name='BusinessHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('is_open', models.BooleanField(default=True)),
                ('open_time', models.TimeField(blank=True, null=True)),
                ('close_time', models.TimeField(blank=True, null=True)),
                ('ai_behavior_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_hours', to='ai_behavior.aibehaviorconfig')),
            ],
            options={
                'unique_together': {('ai_behavior_config', 'day')},
            },
        ),
    ]
