# Generated by Django 6.0 on 2026-01-07 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('STORE_MANAGER', 'Store Manager'), ('STAFF', 'Staff')], default='STAFF', max_length=20),
        ),
    ]
