# Generated by Django 6.0 on 2026-01-06 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('price_list', '0002_alter_brand_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('call_type', models.CharField(choices=[('AI_RESOLVED', 'AI Resolved'), ('WARM_TRANSFER', 'Warm Transfer'), ('DROPPED', 'Dropped'), ('APPOINTMENT', 'Appointment')], max_length=20)),
                ('outcome', models.CharField(blank=True, choices=[('QUOTE_PROVIDED', 'Quote Provided'), ('APPOINTMENT_BOOKED', 'Appointment Booked'), ('ESCALATED', 'Escalated to Technician'), ('CALL_DROPPED', 'Call Dropped')], max_length=30, null=True)),
                ('duration', models.CharField(max_length=10)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField()),
                ('audio_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calls', to='price_list.repairtype')),
            ],
        ),
        migrations.CreateModel(
            name='CallTranscript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker', models.CharField(choices=[('AI', 'AI'), ('CUSTOMER', 'Customer')], max_length=10)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcripts', to='callLogs.callsession')),
            ],
        ),
    ]
