# Generated by Django 6.0 on 2026-01-06 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callLogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callsession',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
