# Generated by Django 6.0 on 2026-01-10 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('price_list', '0004_alter_pricelist_unique_together'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200)),
                ('client_email', models.EmailField(max_length=254)),
                ('client_phone', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('serial_no', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='price_list.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='price_list.category')),
                ('device_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='price_list.devicemodel')),
                ('repair_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='price_list.repairtype')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='store.store')),
            ],
            options={
                'unique_together': {('store', 'date', 'start_time')},
            },
        ),
        migrations.CreateModel(
            name='StoreSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('open_time', models.TimeField(blank=True, null=True)),
                ('close_time', models.TimeField(blank=True, null=True)),
                ('is_open', models.BooleanField(default=True)),
                ('slots_per_hour', models.PositiveSmallIntegerField(default=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='store.store')),
            ],
            options={
                'unique_together': {('store', 'day')},
            },
        ),
    ]
