# Generated by Django 6.0 on 2026-01-07 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(choices=[('SOFTWARE_ISSUE', 'Software Issues'), ('UNKNOWN_DEVICE', 'Unknown Device'), ('PRICE_NEGOTIATION', 'Price Negotiation'), ('WARRANTY_QUESTIONS', 'Warranty Questions'), ('ANGRY_CUSTOMER', 'Angry Customer Detected'), ('OTHER', 'Other')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransferContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_contacts', to='store.store')),
            ],
            options={
                'unique_together': {('store', 'phone_number')},
            },
        ),
        migrations.CreateModel(
            name='StoreTransferRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='call_transfer.transfercondition')),
                ('transfer_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='call_transfer.transfercontact')),
            ],
        ),
    ]
