# Generated by Django 6.0 on 2026-01-11 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('call_transfer', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StoreTransferRule',
            new_name='CallTransfer',
        ),
    ]
