# Generated by Django 6.0 on 2026-01-11 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call_transfer', '0002_rename_storetransferrule_calltransfer'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calltransfer',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.store'),
            preserve_default=False,
        ),
    ]
