# Generated by Django 6.0 on 2026-02-02 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call_transfer', '0003_calltransfer_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfercontact',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
