# Generated by Django 6.0 on 2026-01-09 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAPIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='store.store')),
            ],
        ),
        migrations.CreateModel(
            name='AIModelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_version', models.CharField(choices=[('GPT-4.0', 'GPT-4.0 (Recommended)'), ('GPT-3.5-Turbo', 'GPT-3.5 Turbo'), ('GPT-4', 'GPT-4')], default='GPT-40', max_length=20)),
                ('temperature', models.DecimalField(decimal_places=1, default=0.5, max_digits=2)),
                ('max_tokens', models.PositiveIntegerField(default=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_configs', to='store.store')),
            ],
        ),
        migrations.CreateModel(
            name='AIPerformanceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_timeout', models.PositiveIntegerField(default=30)),
                ('retry_attempts', models.PositiveSmallIntegerField(default=1)),
                ('voice_provider', models.CharField(choices=[('google_tts', 'Google TTS'), ('eleven_labs', 'Eleven Labs'), ('amazon_polly', 'Amazon Polly')], default='google_tts', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_configs', to='store.store')),
            ],
        ),
        migrations.CreateModel(
            name='AISpeechToTextConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stt_provider', models.CharField(choices=[('google_speech', 'Google Speech-to-Text'), ('azure_speech', 'Azure Speech'), ('aws_transcribe', 'AWS Transcribe')], default='google_speech', max_length=20)),
                ('language_model', models.CharField(choices=[('english', 'English'), ('spanish', 'Spanish'), ('french', 'French')], default='english', max_length=20)),
                ('enable_punctuation', models.BooleanField(default=True)),
                ('background_noise_suppression', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stt_configs', to='store.store')),
            ],
        ),
    ]
