# Generated by Django 6.0 on 2026-01-09 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_api_key', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aimodelconfig',
            name='store',
        ),
        migrations.RemoveField(
            model_name='aiperformanceconfig',
            name='store',
        ),
        migrations.RemoveField(
            model_name='aispeechtotextconfig',
            name='store',
        ),
        migrations.DeleteModel(
            name='AIAPIKey',
        ),
        migrations.DeleteModel(
            name='AIModelConfig',
        ),
        migrations.DeleteModel(
            name='AIPerformanceConfig',
        ),
        migrations.DeleteModel(
            name='AISpeechToTextConfig',
        ),
    ]
