# Generated by Django 6.0 on 2026-01-09 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_api_key', '0002_remove_aimodelconfig_store_and_more'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='store.store')),
            ],
        ),
        migrations.CreateModel(
            name='Model_Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_version', models.CharField(choices=[('GPT-40', 'GPT-40 (Recommend)'), ('GPT-3.5-Turbo', 'GPT-3.5 Turbo'), ('GPT-4', 'GPT-4')], default='GPT-40', max_length=20)),
                ('temperature', models.DecimalField(decimal_places=1, default=0.5, max_digits=3)),
                ('max_tokens', models.PositiveIntegerField(default=500)),
                ('response_timeout', models.PositiveIntegerField(default=30)),
                ('retry_attempts', models.PositiveSmallIntegerField(default=3)),
                ('voice_provider', models.CharField(choices=[('google_tts', 'Google TTS'), ('eleven_labs', 'Eleven Labs'), ('amazon_polly', 'Amazon Polly')], default='google_tts', max_length=20)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Model_Configuration', to='store.store')),
            ],
        ),
        migrations.CreateModel(
            name='Speech_to_Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stt_provider', models.CharField(choices=[('google_stt', 'Google Speech-to-Text'), ('azure_stt', 'Azure Speech'), ('aws_transcribe', 'AWS Transcribe')], default='google_stt', max_length=20)),
                ('language_model', models.CharField(choices=[('english', 'English'), ('spanish', 'Spanish'), ('french', 'French')], default='english', max_length=10)),
                ('punctuation_auto_correction', models.BooleanField(default=True)),
                ('background_noise_suppression', models.BooleanField(default=True)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Speech_to_Text', to='store.store')),
            ],
        ),
    ]
