# Generated by Django 6.0 on 2026-01-09 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_api_key', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_configuration',
            name='model_version',
            field=models.CharField(choices=[('GPT-4.0', 'GPT-4.0 (Recommend)'), ('GPT-3.5-Turbo', 'GPT-3.5 Turbo'), ('GPT-4', 'GPT-4')], default='GPT-4.0', max_length=20),
        ),
    ]
