# Generated by Django 6.0 on 2026-01-05 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='brand',
            unique_together={('name', 'category')},
        ),
    ]
