# Generated by Django 6.0 on 2026-01-07 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_list', '0002_alter_brand_unique_together'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelist',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='price_lists', to='store.store'),
            preserve_default=False,
        ),
    ]
