# Generated by Django 6.0 on 2026-01-07 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price_list', '0003_pricelist_store'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pricelist',
            unique_together={('store', 'device_model', 'repair_type')},
        ),
    ]
