# Generated by Django 6.0 on 2026-01-10 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('CALLS', 'Calls'), ('SYSTEM', 'System'), ('USER', 'User'), ('APPOINTMENT ', 'Appointment')], max_length=20),
        ),
    ]
